### ISSUE TITLE
Show clock duration

### ISSUE THREAD

**Issue by srid** [koddo/org-clock-statusbar-app#1]
Hi, I come from http://emacs.stackexchange.com/a/7993/2059 and like your app; simpler to setup. I do have one request - can the app be modified to display the clock duration, along with clock task title, in real-time? 

We can modify the .el to periodically send this information via AppleScript, but the OS X app needs to accept and display it. 

See https://github.com/jordonbiondo/osx-org-clock-menubar/blob/master/osx-org-clock-menubar.el for an .el example. This app sends to a HTTP server, but I like the idea of using AppleScript for communication.

**Comment by koddo** [comment]
Hi, Sridhar. I'd say that's totally possible, but I'm sorry, I'm heavily busy right now. I leave this issue open to resolve it later, maybe. But the good news the app is pretty tiny, you could try to modify it yourself. The first git log messages contain links to tutorials I used to write the app, if you are not familiar with objective-c.

**Comment by srid** [comment]
@koddo - thanks for the response! Would you be open to a pull request rewriting this in Swift first? ObjC scares me away. :-)

**Comment by koddo** [comment]
Well, I'm not sure if an app rewritten in swift would share any code with the existing one, and it's easier to start from scratch I guess. And I don't really know which way would take more time. But it seems like you want to try swift, then just do it. We'll have some alternatives, variety is always good.

**Comment by srid** [comment]
Alright! Instead of just cloning this project (in Swift), however, I may as well use this opportunity to write an extensible/generic Menubar app that I had in mind.
