### ISSUE TITLE
Minor update to README.md

### ISSUE THREAD

**Issue by tommoyer** [koddo/org-clock-statusbar-app#2]
If there are quotes in the task headline the clock-in hook silently fails. I would suggest tweaking the clock-in hook slightly to handle quotations in the task headline:

``` emacs-lisp
(add-hook 'org-clock-in-hook (lambda () (call-process "/usr/bin/osascript" nil 0 nil "-e" (concat "tell application \"org-clock-statusbar\" to clock in \"" (replace-regexp-in-string "\"" "-" org-clock-current-task) "\""))))
```

There is probably a better way to do this, but this was the simplest way I could find.

**Comment by koddo** [comment]
Thanks for bug report and suggestion, I have never had tasks with quotes.
I replaced `"-"` with `"\\\\\""`. Looks funny, this is escaping in emacs.

``` Shell
(add-hook 'org-clock-in-hook (lambda () (call-process "/usr/bin/osascript" nil 0 nil "-e" (concat "tell application \"org-clock-statusbar\" to clock in \"" (replace-regexp-in-string "\"" "\\\\\"" org-clock-current-task) "\""))))
```
